spring:
  application:
    name: issues-recovery
  datasource:
    url: jdbc:h2:file:./data/quartzdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  quartz:
    job-store-type: jdbc  # Usar JDBC JobStore para persistência dos jobs no banco de dados
    jdbc:
      initialize-schema: ALWAYS  # Inicializar o esquema de banco de dados do Quartz automaticamente



logging:
  level:
    root: INFO

scheduler:
  webhook-delay: ${WEBHOOK_DELAY:120}

external-apis:

  github:

#    Github não deixa commitar
#    user: "swapseniortest"
#    token: "github pat 11BL6HWAA0Ar0IlTKlqiDe RQslCndDWcXS4APMJu3RTpwOxthqZ1lJLEZjLS3qpD5FFOVUCROVWiENlCg"

    host: "https://api.github.com/repos/"
    values-per-pages: ${VALUE_PER_PAGES:100}
    page-number: ${PAGES:1}
    paths:
      github-issues-api: "issues"
      github-commits-api: "commits"

  webhook-site:
    host: "https://webhook.site/"
    id: ${WEBHOOK_SITE_ID:2eee0978-cf7d-4d88-90e7-0f240918d9a7}