spring:
  application:
    name: issues-recovery


logging:
  level:
    root: INFO

scheduler:
  webhook-delay: ${WEBHOOK_DELAY:86400}

external-apis:

  github:

#    Github não deixa commitar
#    user: "swapseniortest"
#    token: "github pat 11BL6HWAA0Ar0IlTKlqiDe RQslCndDWcXS4APMJu3RTpwOxthqZ1lJLEZjLS3qpD5FFOVUCROVWiENlCg"

    host: "https://api.github.com/repos/"
    values-per-pages: ${VALUE_PER_PAGES:100}
    page-number: ${PAGES:1}
    paths:
      github-issues-api: "issues"
      github-commits-api: "commits"

  webhook-site:
    host: "https://webhook.site/"
    id: ${WEBHOOK_SITE_ID:2bc3a218-9c8a-4ca7-90dd-bbdda7afe2cc}